### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by 0x796935** [Kylemc1413/GameplayModifiersPlus#12]
I installed the Plugin and for example the Smaller/Bigger notes just dissapear 
The Faster/Slower notes despawn and I fail, but the Reverse works...

**Comment by Kylemc1413** [comment]
Please post your configuration file for the mod

**Comment by 0x796935** [comment]
[GameplayModifiersPlusAsTXT.txt](https://github.com/Kylemc1413/GameplayModifiersPlus/files/4673950/GameplayModifiersPlusAsTXT.txt)

**Comment by Kylemc1413** [comment]
Does your system language use . or does it use , to denote decimal separation?

**Comment by 0x796935** [comment]
It uses ,

**Comment by Kylemc1413** [comment]
The issue is likely due to your config values being stored as . but your system reading them from the config as , due to an issue with BS Utils that will be rectified soon-ish, in the meantime you can try making the values lower by a factor of 10 in the config so that they're read in as something normal

**Comment by 0x796935** [comment]
I tried it thanks for the fast answers ^^, maybe you can write it in the README file too at least I didnt find this information in it. 
I am using , now instead of .
Thank you!
