### ISSUE TITLE
Trigger modifiers with keyboard/controller

### ISSUE THREAD

**Issue by nicolasdeory** [Kylemc1413/GameplayModifiersPlus#7]
A really interesting feature in the future could be the ability to trigger modifiers such as note reversal or random bombs via keyboard or (preferably) controller input. It would really make for an awesome VR party, where people who aren't playing the game at a particular moment can still participate.

I haven't delved into the code, if I have the time I'll try to do a PR, but it should be a matter of reusing the code that already is in place to process twitch chat and trigger the modifiers.

**Comment by Kylemc1413** [comment]
That's something i considered doing if i ever got around to refactoring/rewriting the mod. There is nothing stopping people from simply entering commands into twitch chat locally, though, since it doesn't require the person to be streaming or anything, and just needs a twitch chat to be set up to read from

**Comment by nicolasdeory** [comment]
How would I do that? People can chat in my twitch acc even if I'm not streaming?

**Comment by Kylemc1413** [comment]
Yeah the chat is always there, just have to go to the channel page
